import 'package:presshop/features/news/data/models/all_news_modal.dart';
import 'package:presshop/features/news/presentation/pages/news_details_screen_legacy.dart';

const Map<String, String> markerIcons = {
  "accident": "assets/markers/carcrash.png",
  "fire": "assets/markers/fire.png",
  "medical": "assets/markers/medical.png",
  "gun": "assets/markers/gun.png",
  "protest": "assets/markers/fight.png",
  "knife": "assets/markers/knife.png",
  "fight": "assets/markers/fight.png",
};

final List<NewsItem> newsList = [
  NewsItem(
    id: '1',
    title:
        "Councils vow to fight to close migrant hotels as Labour is accused of 'taking the...",
    description:
        "More than a dozen councils have vowed to fight to shut down controversial asylum hotels following accusations the Labour government is taking the side of migrants over Britons. In a victory for the Home Office, the Court of Appeal yesterday overturned an injunction ordering the removal of 138 migrants from the Bell Hotel in Epping, Essex.",
    authorName: "Superstar 25",
    imageUrl:
        "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?q=80&w=300&auto=format&fit=crop",
    date: "10 Sep 2025",
    time: "12:36",
    fullDateTime: "12:36, 10 Sep 2025",
    location: "150 Piccadilly, London W1J 9BR",
    soldCount: 3,
    earnings: 350,
    viewCount: 220,
    isPublished: true,
    isMostViewed: true,
  ),
  NewsItem(
    id: '2',
    title: "Tech Giants Unveil Revolutionary AI Models at Annual Conference",
    description:
        "Leading technology companies gathered today to showcase their latest advancements in artificial intelligence. The new models promise to revolutionize industries ranging from healthcare to finance.",
    authorName: "TechInsider",
    imageUrl:
        "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?q=80&w=300&auto=format&fit=crop",
    date: "11 Sep 2025",
    time: "09:15",
    fullDateTime: "09:15, 11 Sep 2025",
    location: "San Jose, CA",
    soldCount: 15,
    earnings: 1200,
    viewCount: 5400,
    isPublished: true,
    isMostViewed: false,
  ),
  NewsItem(
    id: '3',
    title: "Local Market Thrives Despite Economic Downturn",
    description:
        "The city's central market continues to bustle with activity, defying broader economic trends. Vendors report steady sales of fresh produce and artisanal goods.",
    authorName: "CityBeat",
    imageUrl:
        "https://images.unsplash.com/photo-1483985988355-763728e1935b?q=80&w=300&auto=format&fit=crop",
    date: "09 Sep 2025",
    time: "16:45",
    fullDateTime: "16:45, 09 Sep 2025",
    location: "Market St, Manchester",
    soldCount: 8,
    earnings: 450,
    viewCount: 890,
    isPublished: true,
    isMostViewed: false,
  ),
  NewsItem(
    id: '4',
    title: "Heavy Rains Cause Flooding Across Northern Districts",
    description:
        "Several northern districts were submerged after continuous rainfall for over 48 hours. Authorities have issued evacuation advisories in low-lying areas.",
    authorName: "WeatherDesk",
    imageUrl:
        "https://images.unsplash.com/photo-1501594907352-04cda38ebc29?q=80&w=300&auto=format&fit=crop",
    date: "12 Sep 2025",
    time: "07:30",
    fullDateTime: "07:30, 12 Sep 2025",
    location: "Leeds, UK",
    soldCount: 6,
    earnings: 300,
    viewCount: 1600,
    isPublished: true,
    isMostViewed: true,
  ),
  NewsItem(
    id: '5',
    title: "Startups See Surge in Funding Amid Market Optimism",
    description:
        "Early-stage startups are witnessing a renewed interest from investors as market sentiment improves and new policy reforms take effect.",
    authorName: "BizDaily",
    imageUrl:
        "https://images.unsplash.com/photo-1521791136064-7986c2920216?q=80&w=300&auto=format&fit=crop",
    date: "12 Sep 2025",
    time: "11:10",
    fullDateTime: "11:10, 12 Sep 2025",
    location: "London, UK",
    soldCount: 10,
    earnings: 800,
    viewCount: 3100,
    isPublished: true,
    isMostViewed: false,
  ),
  NewsItem(
    id: '6',
    title: "Championship Final Draws Record Crowd at National Stadium",
    description:
        "Fans packed the national stadium as the championship final delivered a thrilling contest that went down to the last minute.",
    authorName: "SportsWire",
    imageUrl:
        "https://images.unsplash.com/photo-1505842465776-3d90f616310d?q=80&w=300&auto=format&fit=crop",
    date: "08 Sep 2025",
    time: "20:50",
    fullDateTime: "20:50, 08 Sep 2025",
    location: "Wembley, London",
    soldCount: 20,
    earnings: 1500,
    viewCount: 7600,
    isPublished: true,
    isMostViewed: true,
  ),
  NewsItem(
    id: '7',
    title: "New Metro Line Opens, Cutting Commute Time in Half",
    description:
        "The newly inaugurated metro line promises faster and more efficient travel, significantly reducing commute times for daily passengers.",
    authorName: "UrbanNews",
    imageUrl:
        "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?q=80&w=300&auto=format&fit=crop",
    date: "07 Sep 2025",
    time: "10:00",
    fullDateTime: "10:00, 07 Sep 2025",
    location: "Birmingham, UK",
    soldCount: 5,
    earnings: 280,
    viewCount: 980,
    isPublished: true,
    isMostViewed: false,
  ),
  NewsItem(
    id: '8',
    title: "Wildlife Conservation Efforts Show Positive Results",
    description:
        "Conservationists report a steady increase in wildlife populations following sustained protection and habitat restoration efforts.",
    authorName: "GreenEarth",
    imageUrl:
        "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?q=80&w=300&auto=format&fit=crop",
    date: "06 Sep 2025",
    time: "14:25",
    fullDateTime: "14:25, 06 Sep 2025",
    location: "Scotland",
    soldCount: 4,
    earnings: 220,
    viewCount: 740,
    isPublished: true,
    isMostViewed: false,
  ),
  NewsItem(
    id: '9',
    title: "University Introduces AI-Powered Learning Platform",
    description:
        "A leading university has launched an AI-driven platform aimed at personalizing education and improving student outcomes.",
    authorName: "EduTech",
    imageUrl:
        "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?q=80&w=300&auto=format&fit=crop",
    date: "05 Sep 2025",
    time: "09:40",
    fullDateTime: "09:40, 05 Sep 2025",
    location: "Oxford, UK",
    soldCount: 9,
    earnings: 600,
    viewCount: 2100,
    isPublished: true,
    isMostViewed: false,
  ),
  NewsItem(
    id: '10',
    title: "Healthcare Workers Protest Over Staffing Shortages",
    description:
        "Healthcare professionals staged a peaceful protest highlighting staff shortages and increasing workloads in public hospitals.",
    authorName: "HealthWatch",
    imageUrl:
        "https://images.unsplash.com/photo-1580281657521-6c6e7f7b1d96?q=80&w=300&auto=format&fit=crop",
    date: "04 Sep 2025",
    time: "13:55",
    fullDateTime: "13:55, 04 Sep 2025",
    location: "Liverpool, UK",
    soldCount: 7,
    earnings: 420,
    viewCount: 1350,
    isPublished: true,
    isMostViewed: false,
  ),
  NewsItem(
    id: '11',
    title: "Film Festival Celebrates Independent Cinema",
    description:
        "The annual film festival opened with a focus on independent filmmakers and diverse storytelling from around the world.",
    authorName: "CultureNow",
    imageUrl:
        "https://images.unsplash.com/photo-1517602302552-471fe67acf66?q=80&w=300&auto=format&fit=crop",
    date: "03 Sep 2025",
    time: "18:20",
    fullDateTime: "18:20, 03 Sep 2025",
    location: "Edinburgh, UK",
    soldCount: 12,
    earnings: 900,
    viewCount: 3200,
    isPublished: true,
    isMostViewed: true,
  ),
  NewsItem(
    id: '12',
    title: "Retail Sales Rise Ahead of Festive Season",
    description:
        "Retailers report a noticeable increase in sales as consumers begin early shopping ahead of the festive season.",
    authorName: "RetailTrack",
    imageUrl:
        "https://images.unsplash.com/photo-1521335629791-ce4aec67dd47?q=80&w=300&auto=format&fit=crop",
    date: "02 Sep 2025",
    time: "15:10",
    fullDateTime: "15:10, 02 Sep 2025",
    location: "Leicester, UK",
    soldCount: 11,
    earnings: 760,
    viewCount: 2800,
    isPublished: true,
    isMostViewed: false,
  ),
  NewsItem(
    id: '13',
    title: "Fire Breaks Out in Industrial Area, No Casualties Reported",
    description:
        "A major fire erupted in an industrial zone late at night. Firefighters managed to control the blaze within hours.",
    authorName: "LocalAlert",
    imageUrl:
        "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?q=80&w=300&auto=format&fit=crop",
    date: "01 Sep 2025",
    time: "23:40",
    fullDateTime: "23:40, 01 Sep 2025",
    location: "Sheffield, UK",
    soldCount: 6,
    earnings: 360,
    viewCount: 1200,
    isPublished: true,
    isMostViewed: false,
  ),
  NewsItem(
    id: '14',
    title: "Electric Vehicles Gain Popularity in Urban Areas",
    description:
        "Urban residents are increasingly opting for electric vehicles as charging infrastructure improves and costs decline.",
    authorName: "AutoTrends",
    imageUrl:
        "https://images.unsplash.com/photo-1511396274084-9e8d3a46a4a5?q=80&w=300&auto=format&fit=crop",
    date: "31 Aug 2025",
    time: "10:35",
    fullDateTime: "10:35, 31 Aug 2025",
    location: "Bristol, UK",
    soldCount: 14,
    earnings: 1100,
    viewCount: 4100,
    isPublished: true,
    isMostViewed: true,
  ),
  NewsItem(
    id: '15',
    title: "Community Volunteers Clean Up City Park",
    description:
        "Dozens of volunteers came together over the weekend to clean up the city park, promoting environmental awareness.",
    authorName: "CommunityPost",
    imageUrl:
        "https://images.unsplash.com/photo-1520975693411-b7b9a53a7f64?q=80&w=300&auto=format&fit=crop",
    date: "30 Aug 2025",
    time: "08:50",
    fullDateTime: "08:50, 30 Aug 2025",
    location: "Nottingham, UK",
    soldCount: 5,
    earnings: 250,
    viewCount: 900,
    isPublished: true,
    isMostViewed: false,
  ),
];
